apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress
  labels:
    name: wordpress
spec:
  replicas: 1
  selector:
    name: wordpress
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      restartPolicy: Always
      containers:
        - image: wordpress
          name: wordpress
          env:
            - name: WORDPRESS_DB_PASSWORD
              # change this - must match mysql.yaml password
              value: yourpassword
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
              # name must match the volume name below
            - name: wordpress-persistent-storage
              # mount path within the container
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          awsElasticBlockStore:
            volumeID: aws://us-west-2a/{{ volume_id }}
            fsType: ext4
